### ISSUE TITLE
optmize fonts with next/font

### ISSUE THREAD

**Issue by desamtralized** [yieldi-labs/yieldi-app#6]
We're using local fonts + tailwind<br>[https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#local-fonts](https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#local-fonts)<br>[https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#with-tailwind-css](https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#with-tailwind-css)

* Also, remove `@next/font` dependency, using the included `next/font` module

**Comment by MattNguyen** [comment]
@desamtralized - use linear please
